import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  showTable: false,
  isLoading: false,
  names: [
    { label: "Tarun" },
    { label: "Manni" },
    { label: "Tanmay" },
    { label: "Piyush" },
    { label: "Aman" },
    { label: "Hansraj" },
    { label: "Pushpendr" },
    { label: "Ravleen" },
    { label: "Keerti" },
    { label: "Himanshu" },
    { label: "Yashveer" },
    { label: "Shivam" },
    { label: "Nishant" },
    { label: "Umesh" },
    { label: "Puneet" },
    { label: "Mudit" },
    { label: "Sumit" },
    { label: "Hasan" },
    { label: "Dinesh" },
  ],
  headerData: [
    "Date",
    "Days",
    "Trader",
    "Team",
    "Strategy_Name",
    "Strategy_Type",
    "Instruments",
    "Quantity",
    "Trader_PNL",
    "Backtest_PNL",
    "Slippage",
    "Margin",
    "ROI",
    "VIX",
  ],
  rows: [
    {
      Date: "26-07-23",
      Days: "Monday",
      Trader: "Tarun",
      Team: "Tarun",
      Strategy_Name: "abc",
      Strategy_Type: "simple",
      Instruments: "Nifty",
      Quantity: 1800,
      Margin: 100,
      Slippage: "abc",
      ROI: 76987,
      Trader_PNL: 699,
      Backtest_PNL: 700,
      VIX: 34,
    },

    {
      Date: "26-07-23",
      Days: "Monday",
      Trader: "Tarun",
      Team: "Tarun",
      Strategy_Name: "abc",
      Strategy_Type: "simple",
      Instruments: "Nifty",
      Quantity: 1800,
      Margin: 100,
      Slippage: "abc",
      ROI: 76987,
      Trader_PNL: 699,
      Backtest_PNL: 700,
      VIX: 34,
    },

    {
      Date: "26-07-23",
      Days: "Monday",
      Trader: "Tarun",
      Team: "Tarun",
      Strategy_Name: "abc",
      Strategy_Type: "simple",
      Instruments: "Nifty",
      Quantity: 1800,
      Margin: 100,
      Slippage: "abc",
      ROI: 76987,
      Trader_PNL: 699,
      Backtest_PNL: 700,
      VIX: 34,
    },

    {
      Date: "26-07-23",
      Days: "Monday",
      Trader: "Tarun",
      Team: "Tarun",
      Strategy_Name: "abc",
      Strategy_Type: "simple",
      Instruments: "Nifty",
      Quantity: 1800,
      Margin: 100,
      Slippage: "abc",
      ROI: 76987,
      Trader_PNL: 699,
      Backtest_PNL: 700,
      VIX: 34,
    },

    {
      Date: "26-07-23",
      Days: "Monday",
      Trader: "Tarun",
      Team: "Tarun",
      Strategy_Name: "abc",
      Strategy_Type: "simple",
      Instruments: "Nifty",
      Quantity: 1800,
      Margin: 100,
      Slippage: "abc",
      ROI: 76987,
      Trader_PNL: 699,
      Backtest_PNL: 700,
      VIX: 34,
    },

    {
      Date: "26-07-23",
      Days: "Monday",
      Trader: "Tarun",
      Team: "Tarun",
      Strategy_Name: "abc",
      Strategy_Type: "simple",
      Instruments: "Nifty",
      Quantity: 1800,
      Margin: 100,
      Slippage: "abc",
      ROI: 76987,
      Trader_PNL: 699,
      Backtest_PNL: 700,
      VIX: 34,
    },

    {
      Date: "26-07-23",
      Days: "Monday",
      Trader: "Tarun",
      Team: "Tarun",
      Strategy_Name: "abc",
      Strategy_Type: "simple",
      Instruments: "Nifty",
      Quantity: 1800,
      Margin: 100,
      Slippage: "abc",
      ROI: 76987,
      Trader_PNL: 699,
      Backtest_PNL: 700,
      VIX: 34,
    },

    {
      Date: "26-07-23",
      Days: "Monday",
      Trader: "Tarun",
      Team: "Tarun",
      Strategy_Name: "abc",
      Strategy_Type: "simple",
      Instruments: "Nifty",
      Quantity: 1800,
      Margin: 100,
      Slippage: "abc",
      ROI: 76987,
      Trader_PNL: 699,
      Backtest_PNL: 700,
      VIX: 34,
    },

    {
      Date: "26-07-23",
      Days: "Monday",
      Trader: "Tarun",
      Team: "Tarun",
      Strategy_Name: "abc",
      Strategy_Type: "simple",
      Instruments: "Nifty",
      Quantity: 1800,
      Margin: 100,
      Slippage: "abc",
      ROI: 76987,
      Trader_PNL: 699,
      Backtest_PNL: 700,
      VIX: 34,
    },

    {
      Date: "26-07-23",
      Days: "Monday",
      Trader: "Tarun",
      Team: "Tarun",
      Strategy_Name: "abc",
      Strategy_Type: "simple",
      Instruments: "Nifty",
      Quantity: 1800,
      Margin: 100,
      Slippage: "abc",
      ROI: 76987,
      Trader_PNL: 699,
      Backtest_PNL: 700,
      VIX: 34,
    },

    {
      Date: "26-07-23",
      Days: "Monday",
      Trader: "Tarun",
      Team: "Tarun",
      Strategy_Name: "abc",
      Strategy_Type: "simple",
      Instruments: "Nifty",
      Quantity: 1800,
      Margin: 100,
      Slippage: "abc",
      ROI: 76987,
      Trader_PNL: 699,
      Backtest_PNL: 700,
      VIX: 34,
    },

    {
      Date: "26-07-23",
      Days: "Monday",
      Trader: "Tarun",
      Team: "Tarun",
      Strategy_Name: "abc",
      Strategy_Type: "simple",
      Instruments: "Nifty",
      Quantity: 1800,
      Margin: 100,
      Slippage: "abc",
      ROI: 76987,
      Trader_PNL: 699,
      Backtest_PNL: 700,
      VIX: 34,
    },

    {
      Date: "26-07-23",
      Days: "Monday",
      Trader: "Tarun",
      Team: "Tarun",
      Strategy_Name: "abc",
      Strategy_Type: "simple",
      Instruments: "Nifty",
      Quantity: 1800,
      Margin: 100,
      Slippage: "abc",
      ROI: 76987,
      Trader_PNL: 699,
      Backtest_PNL: 700,
      VIX: 34,
    },

    {
      Date: "26-07-23",
      Days: "Monday",
      Trader: "Tarun",
      Team: "Tarun",
      Strategy_Name: "abc",
      Strategy_Type: "simple",
      Instruments: "Nifty",
      Quantity: 1800,
      Margin: 100,
      Slippage: "abc",
      ROI: 76987,
      Trader_PNL: 699,
      Backtest_PNL: 700,
      VIX: 34,
    },

    {
      Date: "26-07-23",
      Days: "Monday",
      Trader: "Tarun",
      Team: "Tarun",
      Strategy_Name: "abc",
      Strategy_Type: "simple",
      Instruments: "Nifty",
      Quantity: 1800,
      Margin: 100,
      Slippage: "abc",
      ROI: 76987,
      Trader_PNL: 699,
      Backtest_PNL: 700,
      VIX: 34,
    },

    {
      Date: "26-07-23",
      Days: "Monday",
      Trader: "Tarun",
      Team: "Tarun",
      Strategy_Name: "abc",
      Strategy_Type: "simple",
      Instruments: "Nifty",
      Quantity: 1800,
      Margin: 100,
      Slippage: "abc",
      ROI: 76987,
      Trader_PNL: 699,
      Backtest_PNL: 700,
      VIX: 34,
    },

    {
      Date: "26-07-23",
      Days: "Monday",
      Trader: "Tarun",
      Team: "Tarun",
      Strategy_Name: "abc",
      Strategy_Type: "simple",
      Instruments: "Nifty",
      Quantity: 1800,
      Margin: 100,
      Slippage: "abc",
      ROI: 76987,
      Trader_PNL: 699,
      Backtest_PNL: 700,
      VIX: 34,
    },

    {
      Date: "26-07-23",
      Days: "Monday",
      Trader: "Tarun",
      Team: "Tarun",
      Strategy_Name: "abc",
      Strategy_Type: "simple",
      Instruments: "Nifty",
      Quantity: 1800,
      Margin: 100,
      Slippage: "abc",
      ROI: 76987,
      Trader_PNL: 699,
      Backtest_PNL: 700,
      VIX: 34,
    },

    {
      Date: "26-07-23",
      Days: "Monday",
      Trader: "Tarun",
      Team: "Tarun",
      Strategy_Name: "abc",
      Strategy_Type: "simple",
      Instruments: "Nifty",
      Quantity: 1800,
      Margin: 100,
      Slippage: "abc",
      ROI: 76987,
      Trader_PNL: 699,
      Backtest_PNL: 700,
      VIX: 34,
    },

    {
      Date: "26-07-23",
      Days: "Monday",
      Trader: "Tarun",
      Team: "Tarun",
      Strategy_Name: "abc",
      Strategy_Type: "simple",
      Instruments: "Nifty",
      Quantity: 1800,
      Margin: 100,
      Slippage: "abc",
      ROI: 76987,
      Trader_PNL: 699,
      Backtest_PNL: 700,
      VIX: 34,
    },

    {
      Date: "26-07-23",
      Days: "Monday",
      Trader: "Tarun",
      Team: "Tarun",
      Strategy_Name: "abc",
      Strategy_Type: "simple",
      Instruments: "Nifty",
      Quantity: 1800,
      Margin: 100,
      Slippage: "abc",
      ROI: 76987,
      Trader_PNL: 699,
      Backtest_PNL: 700,
      VIX: 34,
    },

    {
      Date: "26-07-23",
      Days: "Monday",
      Trader: "Tarun",
      Team: "Tarun",
      Strategy_Name: "abc",
      Strategy_Type: "simple",
      Instruments: "Nifty",
      Quantity: 1800,
      Margin: 100,
      Slippage: "abc",
      ROI: 76987,
      Trader_PNL: 699,
      Backtest_PNL: 700,
      VIX: 34,
    },

    {
      Date: "26-07-23",
      Days: "Monday",
      Trader: "Tarun",
      Team: "Tarun",
      Strategy_Name: "abc",
      Strategy_Type: "simple",
      Instruments: "Nifty",
      Quantity: 1800,
      Margin: 100,
      Slippage: "abc",
      ROI: 76987,
      Trader_PNL: 699,
      Backtest_PNL: 700,
      VIX: 34,
    },

    {
      Date: "26-07-23",
      Days: "Monday",
      Trader: "Tarun",
      Team: "Tarun",
      Strategy_Name: "abc",
      Strategy_Type: "simple",
      Instruments: "Nifty",
      Quantity: 1800,
      Margin: 100,
      Slippage: "abc",
      ROI: 76987,
      Trader_PNL: 699,
      Backtest_PNL: 700,
      VIX: 34,
    },

    {
      Date: "26-07-23",
      Days: "Monday",
      Trader: "Tarun",
      Team: "Tarun",
      Strategy_Name: "abc",
      Strategy_Type: "simple",
      Instruments: "Nifty",
      Quantity: 1800,
      Margin: 100,
      Slippage: "abc",
      ROI: 76987,
      Trader_PNL: 699,
      Backtest_PNL: 700,
      VIX: 34,
    },

    {
      Date: "26-07-23",
      Days: "Monday",
      Trader: "Tarun",
      Team: "Tarun",
      Strategy_Name: "abc",
      Strategy_Type: "simple",
      Instruments: "Nifty",
      Quantity: 1800,
      Margin: 100,
      Slippage: "abc",
      ROI: 76987,
      Trader_PNL: 699,
      Backtest_PNL: 700,
      VIX: 34,
    },

    {
      Date: "26-07-23",
      Days: "Monday",
      Trader: "Tarun",
      Team: "Tarun",
      Strategy_Name: "abc",
      Strategy_Type: "simple",
      Instruments: "Nifty",
      Quantity: 1800,
      Margin: 100,
      Slippage: "abc",
      ROI: 76987,
      Trader_PNL: 699,
      Backtest_PNL: 700,
      VIX: 34,
    },
  ],
};

const dataSlice = createSlice({
  name: "data",
  initialState,
  reducers: {
    toggleTable(state) {
      state.isLoading = false;
      state.showTable = true;
    },
    toggleLoading(state) {
      state.isLoading = true;
    },
  },
});

export const dataSliceActions = dataSlice.actions;

export default dataSlice.reducer;
