import React from "react";
import TableBody from "@mui/material/TableBody";
import { styled } from "@mui/material/styles";
import TableCell, { tableCellClasses } from "@mui/material/TableCell";
import TableRow from "@mui/material/TableRow";

const TableData = () => {
  const StyledTableRow = styled(TableRow)(({ theme }) => ({
    "&:nth-of-type(odd)": {
      backgroundColor: theme.palette.action.hover,
    },
    // hide last border
    "&:last-child td, &:last-child th": {
      border: 0,
    },
  }));
  const StyledTableCell = styled(TableCell)(({ theme }) => ({
    [`&.${tableCellClasses.head}`]: {
      backgroundColor: theme.palette.common.black,
      color: theme.palette.common.white,
    },
    [`&.${tableCellClasses.body}`]: {
      fontSize: 14,
    },
  }));

  const rows = [
    {
      Date:"26-07-23",
      Days:"Monday",
      Name:"Tarun",
      Variant:"abc",
      Type:"simple",
      Instrument:"Nifty",
      Quantity:1800,
      Margin:100,
      Slippage:"abc",
      ROT:76987,
      PNL:700
},
    {
      Date:"26-07-23",
      Days:"Monday",
      Name:"Tarun",
      Variant:"abc",
      Type:"simple",
      Instrument:"Nifty",
      Quantity:1800,
      Margin:100,
      Slippage:"abc",
      ROT:76987,
      PNL:700
},
    {
      Date:"26-07-23",
      Days:"Monday",
      Name:"Tarun",
      Variant:"abc",
      Type:"simple",
      Instrument:"Nifty",
      Quantity:1800,
      Margin:100,
      Slippage:"abc",
      ROT:76987,
      PNL:700
},
    {
      Date:"26-07-23",
      Days:"Monday",
      Name:"Tarun",
      Variant:"abc",
      Type:"simple",
      Instrument:"Nifty",
      Quantity:1800,
      Margin:100,
      Slippage:"abc",
      ROT:76987,
      PNL:700
},
    {
      Date:"26-07-23",
      Days:"Monday",
      Name:"Tarun",
      Variant:"abc",
      Type:"simple",
      Instrument:"Nifty",
      Quantity:1800,
      Margin:100,
      Slippage:"abc",
      ROT:76987,
      PNL:700
},
    {
      Date:"26-07-23",
      Days:"Monday",
      Name:"Tarun",
      Variant:"abc",
      Type:"simple",
      Instrument:"Nifty",
      Quantity:1800,
      Margin:100,
      Slippage:"abc",
      ROT:76987,
      PNL:700
},
    {
      Date:"26-07-23",
      Days:"Monday",
      Name:"Tarun",
      Variant:"abc",
      Type:"simple",
      Instrument:"Nifty",
      Quantity:1800,
      Margin:100,
      Slippage:"abc",
      ROT:76987,
      PNL:700
},
    {
      Date:"26-07-23",
      Days:"Monday",
      Name:"Tarun",
      Variant:"abc",
      Type:"simple",
      Instrument:"Nifty",
      Quantity:1800,
      Margin:100,
      Slippage:"abc",
      ROT:76987,
      PNL:700
},
    {
      Date:"26-07-23",
      Days:"Monday",
      Name:"Tarun",
      Variant:"abc",
      Type:"simple",
      Instrument:"Nifty",
      Quantity:1800,
      Margin:100,
      Slippage:"abc",
      ROT:76987,
      PNL:700
},
    {
      Date:"26-07-23",
      Days:"Monday",
      Name:"Tarun",
      Variant:"abc",
      Type:"simple",
      Instrument:"Nifty",
      Quantity:1800,
      Margin:100,
      Slippage:"abc",
      ROT:76987,
      PNL:700
},
    {
      Date:"26-07-23",
      Days:"Monday",
      Name:"Tarun",
      Variant:"abc",
      Type:"simple",
      Instrument:"Nifty",
      Quantity:1800,
      Margin:100,
      Slippage:"abc",
      ROT:76987,
      PNL:700
},
    {
      Date:"26-07-23",
      Days:"Monday",
      Name:"Tarun",
      Variant:"abc",
      Type:"simple",
      Instrument:"Nifty",
      Quantity:1800,
      Margin:100,
      Slippage:"abc",
      ROT:76987,
      PNL:700
},
    {
      Date:"26-07-23",
      Days:"Monday",
      Name:"Tarun",
      Variant:"abc",
      Type:"simple",
      Instrument:"Nifty",
      Quantity:1800,
      Margin:100,
      Slippage:"abc",
      ROT:76987,
      PNL:700
},
    {
      Date:"26-07-23",
      Days:"Monday",
      Name:"Tarun",
      Variant:"abc",
      Type:"simple",
      Instrument:"Nifty",
      Quantity:1800,
      Margin:100,
      Slippage:"abc",
      ROT:76987,
      PNL:700
},
    {
      Date:"26-07-23",
      Days:"Monday",
      Name:"Tarun",
      Variant:"abc",
      Type:"simple",
      Instrument:"Nifty",
      Quantity:1800,
      Margin:100,
      Slippage:"abc",
      ROT:76987,
      PNL:700
},
    {
      Date:"26-07-23",
      Days:"Monday",
      Name:"Tarun",
      Variant:"abc",
      Type:"simple",
      Instrument:"Nifty",
      Quantity:1800,
      Margin:100,
      Slippage:"abc",
      ROT:76987,
      PNL:700
},
    {
      Date:"26-07-23",
      Days:"Monday",
      Name:"Tarun",
      Variant:"abc",
      Type:"simple",
      Instrument:"Nifty",
      Quantity:1800,
      Margin:100,
      Slippage:"abc",
      ROT:76987,
      PNL:700
},
    {
      Date:"26-07-23",
      Days:"Monday",
      Name:"Tarun",
      Variant:"abc",
      Type:"simple",
      Instrument:"Nifty",
      Quantity:1800,
      Margin:100,
      Slippage:"abc",
      ROT:76987,
      PNL:700
},
    {
      Date:"26-07-23",
      Days:"Monday",
      Name:"Tarun",
      Variant:"abc",
      Type:"simple",
      Instrument:"Nifty",
      Quantity:1800,
      Margin:100,
      Slippage:"abc",
      ROT:76987,
      PNL:700
},
    {
      Date:"26-07-23",
      Days:"Monday",
      Name:"Tarun",
      Variant:"abc",
      Type:"simple",
      Instrument:"Nifty",
      Quantity:1800,
      Margin:100,
      Slippage:"abc",
      ROT:76987,
      PNL:700
},
    {
      Date:"26-07-23",
      Days:"Monday",
      Name:"Tarun",
      Variant:"abc",
      Type:"simple",
      Instrument:"Nifty",
      Quantity:1800,
      Margin:100,
      Slippage:"abc",
      ROT:76987,
      PNL:700
},
    {
      Date:"26-07-23",
      Days:"Monday",
      Name:"Tarun",
      Variant:"abc",
      Type:"simple",
      Instrument:"Nifty",
      Quantity:1800,
      Margin:100,
      Slippage:"abc",
      ROT:76987,
      PNL:700
},
    {
      Date:"26-07-23",
      Days:"Monday",
      Name:"Tarun",
      Variant:"abc",
      Type:"simple",
      Instrument:"Nifty",
      Quantity:1800,
      Margin:100,
      Slippage:"abc",
      ROT:76987,
      PNL:700
},
  ]
  const headerData = [
    "Date",
    "Days",
    "Name",
    "Variant",
    "Type",
    "Instrument",
    "Quantity",
    "Margin",
    "Slippage",
    "ROT",
    "PNL",
  ];

  return (
    <TableBody>
      {rows.map((row,index) => (
        <StyledTableRow key={index}>
          <StyledTableCell  align="center" >
            {index}
          </StyledTableCell>
            {headerData.map(item=><StyledTableCell key={item}  align="center" >{row[item]}</StyledTableCell>)}
        </StyledTableRow>
      ))}
    </TableBody>
  );
};

export default TableData;
